### ISSUE TITLE
error: anonymous function at /nix/store/..eval-config.nix:11:1 called with unexpected argument 'packages'

### ISSUE THREAD

**Issue by aleeusgr** [aleeusgr/nix-things#13]
This
https://github.com/aleeusgr/nix-things/blob/1476e0ae01dc2d0370c5bc06b4d5c16b9315a523/flake.nix#L54-L57

causes `nixos-rebuild` to give:
```
        error: anonymous function at /nix/store/n0f21zpy9w90sa9v75iwx6fmk897z3nw-source/nixos/lib/eval-config.nix:11:1 called with unexpected argument 'packages'

       at /nix/store/n0f21zpy9w90sa9v75iwx6fmk897z3nw-source/flake.nix:22:11:

           21|         nixosSystem = args:
           22|           import ./nixos/lib/eval-config.nix (
             |           ^
           23|             args // {
```
_Originally posted by @aleeusgr in https://github.com/aleeusgr/nix-things/issues/10#issuecomment-1333334760_

**Comment by aleeusgr** [comment]
https://github.com/aleeusgr/nix-things/blob/1476e0ae01dc2d0370c5bc06b4d5c16b9315a523/flake.nix#L54-L57

**Comment by NobbZ** [comment]
The `nixosSystem` function does not know about an argument `packages`, you probably ment to use a module which adds those to `environment.systemPackages`.

**Comment by aleeusgr** [comment]
So I should have imports in flake.nix, and then put this snippet in configuration.nix?

**Comment by NobbZ** [comment]
You need to set `environment.systemPackages` in a module.

I am not sure what you want to import, nor what `configuration.nix` is, other than an arbitrary file name.

**Comment by aleeusgr** [comment]
OK, I needed this. Thank you, @NobbZ 

## TODO: test `cardano-node` using local clone of nixpkgs.
 [7.1.2. Adding Custom Packages](https://nixos.org/manual/nixos/stable/index.html#sec-custom-packages)

[Alternative solution](https://github.com/aleeusgr/nix-things/issues/10)
